from setuptools import setup, find_packages
setup(
    name='soundctm-dit',
    version='1.0.0',
    url='https://github.com/sony/soundctm.git',
    author='Koichi Saito',
    author_email="koichi.saito@sony.com",
    description='Training and inference tools for SoundCTM',
    packages=find_packages(),
    install_requires=[
        "torch",
        "torchvision",
        "torchaudio",
        "torchlibrosa",
        "accelerate",
        "diffusers",
        "transformers",
        "datasets",
        "descript-audiotools",
        "h5py",
        "ftfy",
        "wget",
        "x_transformers",
        "descript-audio-codec",
        "dac",
        "laion-clap",
        "prettytable",
        "pandas",
        "timm",
        "pedalboard",
        "hear21passt @ git+https://github.com/kkoutini/passt_hear21#egg=hear21passt",
        "numba",
        "numpy==1.24.3",
    ],
    python_requires='>=3.9',
)
